### ISSUE TITLE
Syntax error in the "Santa" code (25th)

### ISSUE THREAD

**Issue by choroba** [perladvent/Perl-Advent#102]
The Santa code from the 25th doesn't work for me:

```
Backslash found where operator expected at ./1.pl line 64, near "')'\"
        (Missing operator before \?)
syntax error at ./1.pl line 19, near ")) "
syntax error at ./1.pl line 64, near "')'\"
Can't find string terminator "'" anywhere before EOF at ./1.pl line 65.
```

**Comment by 2shortplanks** [comment]
Well, shucks. I'll take a look at it.

FWIW: I didn't code this myself, it's the output from Acme::EyeDrops

--
Mark Fowler

**Comment by briandfoy** [comment]
It looks like the pattern got off in a few places.

The program is:

    #!perl

    print "Merry Christmas From The Perl Advent Calendar"

The shape name is santa2.
