### ISSUE TITLE
2018 Month is January

### ISSUE THREAD

**Issue by openstrike** [perladvent/Perl-Advent#116]
This might not matter at all but I see that for 2018 the month in all the article filenames is January whereas in previous years it had always been December. eg. https://github.com/perladvent/Perl-Advent/blob/y2018/2018/articles/2018-01-01.pod vs. https://github.com/perladvent/Perl-Advent/blob/y2018/2017/articles/2017-12-01.pod

Will this cause problems? Should we rename them now?

**Comment by 2shortplanks** [comment]
Yeah, I literally just noticed that while doing my first build five minutes
ago.

I renamed them in my most recent push

**Comment by openstrike** [comment]
Thanks, Mark.
