### ISSUE TITLE
write a .t that checks pod for required things

### ISSUE THREAD

**Issue by karenetheridge** [perladvent/Perl-Advent#14]
- pod syntax
- necessary headers
- other things that authors may not have noticed are needed

**Comment by briandfoy** [comment]
I'd inclined to take this on if someone give particulars for the necessary headers. I guess I could look around and figure it out. That is, unless someone else has already called dibs.

**Comment by oalders** [comment]
> I'd inclined to take this on if someone give particulars for the necessary headers. 

From a quick scan, it looks like `Title`, 'Topic` and `Author`.

**Comment by briandfoy** [comment]
This is done and can be closed.
