### ISSUE TITLE
Archive page ends in 2014

### ISSUE THREAD

**Issue by ap** [perladvent/Perl-Advent#140]
The list of Previous Calendars on https://perladvent.org/archives.html only goes up to 2014, even though 2015 through 2020 are also reachable by editing the URL.

**Comment by oalders** [comment]
This looks to be mostly a matter of running `perl mkarchives .`, but I'm still not quite clear on what, if anything, else needs to happen in order for the site to be generated.

**Comment by thibaultduponchelle** [comment]
From my understanding:

- Old calendars (2000-2010) are plain html (versioned) so don't need any generation.
- Recent calendars need to be processed using `advcal -c advent.ini` (last calendar seems to need it daily during December)
- `archives.html`, `archives-AZ.html` and `archives-Yd.html` are created from `perl mkarchives`
- `index.html` is plain html versioned  

Just running `perl mkarchives` should be enough.

**Comment by thibaultduponchelle** [comment]
Fixed
