### ISSUE TITLE
Submit past articles to https://github.com/davorg/learncpan

### ISSUE THREAD

**Issue by oalders** [perladvent/Perl-Advent#141]
We should have some kind of a script that can create the CSV rows required by learncpan. We can add years 2000-2021 before the 2022 edition launches.

**Comment by oalders** [comment]
Does that sound reasonable @davorg?

**Comment by davorg** [comment]
It really does :-)

**Comment by davorg** [comment]
If you're working on this, please note that the first few(?) years of the Perl Advent Calendar just contained the POD of interesting modules. Those entries aren't particularly useful and I'd rather not spend time removing them.

**Comment by thibaultduponchelle** [comment]
@davorg @kjt299 I think year 2000 and 2001 could be ignored, requested change on #168

**Comment by oalders** [comment]
Closed via https://github.com/davorg/learncpan/pull/12

**Comment by oalders** [comment]
@kjt299 do you still have your script handy? We could add the 2022 articles now.

**Comment by simbabque** [comment]
All done. Thank you @kjt299!
