### ISSUE TITLE
Article on getting started with perlimports

### ISSUE THREAD

**Issue by oalders** [perladvent/Perl-Advent#148]
Which Perl module do you want to write about:

App::perlimports

Please give a short description of the article you want to write. Two to three sentences is fine:

perlimports can now auto-create config files, which makes getting up and running much faster than it once was. I'd like to demonstrate the basics of cleaning up some old code in just a few minutes.

**Comment by briandfoy** [comment]
There's now a script to start your article for you and show off the pod enhancements you can use:

    perl script/new_article

Good luck!

**Comment by thibaultduponchelle** [comment]
Not needed 🤷🏼 😄
