### ISSUE TITLE
Archive links 404 on single digit dates in 2010

### ISSUE THREAD

**Issue by n1vux** [perladvent/Perl-Advent#15]
As noted in comment on #4 , but simpler to solve (and currently visitor visible), so maybe this deserves a separate issue:

Archives pages http://perladvent.org/archives-Yd.html and ./archives-AZ.html are linking to 2010 uniformly as ./2010/dd but the pages are at ./2010/9/ , so there are (at least) 9 pages that appear to 404 from the Archive link.

Could be fixed with rewrite, symlink, meta redirect, or just editing the two Archives files to add q(0)x9 each.

(IIRC on the 2nd generation of Advent's PM.org WEBdav server, we had symlinks instead of rewrite rules. My peek at Archives today was prompted by PM.org discussion about moving that static service to "Grandfathered" twighlight status.)

**Comment by oalders** [comment]
We should add a script to crawl the deployed site for 404s.

**Comment by simbabque** [comment]
We could throw https://metacpan.org/pod/Test::Pod::No404s at the articles. Maybe we can even write a test suite for them and have a github action that runs on article PRs.

**Comment by oalders** [comment]
I believe this is fixed now.
