### ISSUE TITLE
Article about Carton bundler

### ISSUE THREAD

**Issue by x1mandi** [perladvent/Perl-Advent#150]
Which Perl module do you want to write about:

Carton

Please give a short description of the article you want to write. Two to three sentences is fine:
I was thinking about an article about the logistic area of Santa's warehouse, e.g how the elves are doing the packing of Perl scripts using Carton on a machine with internet connection, then distributing the code to the servers without internet connection, having all modules installed by Carton.
This is a technique I came up with at my former employer to be able to use modules on servers without internet.

I hope this is a good candidate for an article.

**Comment by briandfoy** [comment]
There's now a script to start your article for you and show off the pod enhancements you can use:

    perl script/new_article

Good luck!

**Comment by x1mandi** [comment]
Just wanted to let You know, that I am still working on the article. I think I am going to publish a draft version this weekend.

**Comment by thibaultduponchelle** [comment]
Article in #193

**Comment by thibaultduponchelle** [comment]
day 21

**Comment by oalders** [comment]
Thanks @x1mandi!
