### ISSUE TITLE
Assign me one or more articles to edit as you see fit

### ISSUE THREAD

**Issue by s1037989** [perladvent/Perl-Advent#159]
Are there any areas in particular you feel you'd be well suited to edit?

You only need to answer this question if you'd like to restrict your
participation to certain topics. Otherwise, we'll just assign you articles to
review as we see fit.

**Comment by thibaultduponchelle** [comment]
👍🏼 

Would you kindly look at "Santa is on GitHub" draft? I added you as collaborator to my private repository 😃

**Comment by s1037989** [comment]
> Would you kindly look at "Santa is on GitHub" draft? I added you as collaborator to my private repository smiley

I would be happy to, can you provide a link?  I'm struggling to find a private repository of yours, or any place where I might find this draft.

**Comment by thibaultduponchelle** [comment]
If you want, there is my second article #169 to edit 😄

**Comment by thibaultduponchelle** [comment]
One more? 😄  #178

**Comment by thibaultduponchelle** [comment]
May I use your time once again? (#196)
