### ISSUE TITLE
Santa's Helpers Embrace the Shell

### ISSUE THREAD

**Issue by s1037989** [perladvent/Perl-Advent#170]
**Which Perl module do you want to write about:**

A new command line tool called [jp](https://github.com/stefanadams/jp) -- powered by [Mojolicious](https://mojolicious.org) -- for parsing JSON, written in Perl that uses Perl syntax in one of the command's optional arguments.

**Please give a short description of the article you want to write. Two to three sentences is fine:**

I want to promote the use of command line tools and demonstrate the value and power of this new `jp` tool for parsing JSON on the command line which supports using Perl data structures and logic to extract exactly the desired data.

**Comment by s1037989** [comment]
My article is actually already written, and if my proposal is accepted, I'll get a PR for it right away!

**Comment by s1037989** [comment]
Thanks!  I'll do my best to submit it properly.  Let me know where I go wrong.

**Comment by oalders** [comment]
Sounds great, @s1037989! We appreciate the contribution. 😄

**Comment by thibaultduponchelle** [comment]
day 13
