### ISSUE TITLE
Article about cgi_this

### ISSUE THREAD

**Issue by simbabque** [perladvent/Perl-Advent#176]
Which Perl module do you want to write about: 
https://metacpan.org/pod/App::CGIThis

Please give a short description of the article you want to write. Two to three sentences is fine:
As is the case in most public sector institutions, a lot of the tools at the North pole are out of date. The elves often need to work with terrible spaghetti CGI scripts that are still around from the olden days. But of course the original development infrastructure has long since gone away, because of that sad sysadmin one Christmas who really wanted a new Debian Woody machine, so what were they going to do? Since that selfless act of giving their last machine to a fellow techie in need, they use `cgi_this` whenever they have to debug one of the old scripts, and it suits their needs well.

**Comment by oalders** [comment]
https://perladvent.org/2022/2022-12-04.html \o/
