### ISSUE TITLE
St. Nich's Reindeers Need Water!

### ISSUE THREAD

**Issue by oodler577** [perladvent/Perl-Advent#182]
Which Perl module do you want to write about:

**Util::H2O**

Please give a short description of the article you want to write. Two to three sentences is fine:

With Santa's sleigh having to be moving at 650 miles per second while simultaneously visiting 822.6 homes with Children per _second_ [1], one may rightly assume that His reindeer are might thirsty for some high quality H2O! While a Perl module won't actually water Dunder and Blixem, there is one that comes around every so often that can make Perl more fun and productive, even for existing code! On this day of Advent, I will discuss the module, **Util::H2O**.

_References_:

1. According to the peered reviewed and legendary Internet report on, "_The Physics of Santa_"..

**Comment by thibaultduponchelle** [comment]
@oodler577 Gentle reminder 😄

**Comment by oodler577** [comment]
Yes, sir. Thank you for the reminder. I forgot to set my alarm xD...oh wait that was for the other one. ON IT! Cheers!
