### ISSUE TITLE
New article: Colored Chart

### ISSUE THREAD

**Issue by lichtkind** [perladvent/Perl-Advent#186]
Which Perl module do you want to write about:

Chart and Graphics::Toolkit::Color (a direct dependency and part of Chart feature set)

Please give a short description of the article you want to write. Two to three sentences is fine:

How to insert into a regular bar chart some special data points to highlight something via converting it into a composite chart. Some tips how to make it beautiful and how to employ the ->complementary method to get a nice fitting color set fast.

**Comment by oalders** [comment]
Looking forward to reading it @lichtkind!

**Comment by oalders** [comment]
There's a script you can use to get started. See https://github.com/perladvent/Perl-Advent/issues/147#issuecomment-1200134125

**Comment by lichtkind** [comment]
my article is now fully researched and half written and i have plenty material, should i cut it in two?

**Comment by openstrike** [comment]
Ideally not. As this is an advent calendar every day should be about a different subject/module.

Your article doesn't need to be exhaustive. Instead you can just give one or two examples of using the module and hint at the other possibilities to encourage readers to go to the POD for further detail. Think of it as a little taster piece.

As an example, here is [the old Dancer entry](https://perladvent.org/2012/2012-12-05.html). Dancer is a big module with lots to explain but the article is nice and short, doesn't overwhelm the reader and gives just a flavour of what [Dancer](https://metacpan.org/module/Dancer) can do.

**Comment by lichtkind** [comment]
sure just wanted help because you seem to still need some and API of chart is quite tiny (many properties though) i concentrate on the on a few practical bits that aren't directly documented yet.

**Comment by oalders** [comment]
At this point we really do need articles and I don't want someone to have to sit down and write eight or 10 at the last minute just to make it to 24. 

If you think there's a clean way to do this in more than one article, I'd be interested to see what you have. Maybe you could sketch out what you would cover in each and we could see if that's a good fit.

**Comment by lichtkind** [comment]
alright lets have one where itw about tweaking the optics and the other how to set up a mass factory for producing charts

**Comment by oalders** [comment]
If you could create a new issue for the other article, that would help is in tracking how close we are to reaching 24.

**Comment by lichtkind** [comment]
sorry just saw you last post after submitting, i mean you dont have to take the second anyway

**Comment by thibaultduponchelle** [comment]
It’s Ok @lichtkind just open another “issue” for us to follow the number and status of articles. 2 articles - 2 issues 😄

**Comment by lichtkind** [comment]
allright other article is now #199, please tell me how to make one inter article link or insert in yourself please, in second article (at the factory) is the phrase "previous calendar leaf". please link that to the first one. Thanks

**Comment by thibaultduponchelle** [comment]
Day 24
