### ISSUE TITLE
bug in start script

### ISSUE THREAD

**Issue by lichtkind** [perladvent/Perl-Advent#188]
Cheers,

in script/new_article there is:

```html
<p>Some para</a>
```
This is back to Pod. For big blocks of HTML, including blank lines,
use C<=begin html>.

=begin html

```html
<p>Some para</a>
```

the closing tags should be `</p>` ?

**Comment by briandfoy** [comment]
heh, took a minute to figure out the issue had some HTML swallowed in it. I had an `</a>` as the closing tag for `<p>` in a couple of places.

**Comment by oalders** [comment]
Ah, I didn't notice that. I edited @lichtkind's comment to make that clearer.

**Comment by lichtkind** [comment]
great work
