### ISSUE TITLE
Buy a christmas with a pEFL frontend of SVG::ChristmasTree

### ISSUE THREAD

**Issue by MaxPerl** [perladvent/Perl-Advent#191]
Which Perl module do you want to write about:

pEFL

Please give a short description of the article you want to write. Two to three sentences is fine:

pEFL is a very new module I wrote. It is a binding to the enlightenment foundation libraries, especially the Elementary GUI library. So I would like to write a little pEFL-frontend to SVG::ChristmasTree. One could pattern a christmas tree with several options (layers, leaf_color etc.) and with a buy button the app closes.
perhaps it would be possible to add a option to use MathPerl::Fractal::ChristmasTree (see #144) for creating the tree, too

**Comment by MaxPerl** [comment]
thank you very much for accepting proposal :-)

**Comment by oalders** [comment]
Article in #196

**Comment by thibaultduponchelle** [comment]
day 8

**Comment by oalders** [comment]
Discussion at https://www.reddit.com/r/perl/comments/zg3kcs/perl_advent_calendar_2022_day_8_a_perlmas_tree/
