### ISSUE TITLE
Compiling modules in difficult environments

### ISSUE THREAD

**Issue by x1mandi** [perladvent/Perl-Advent#195]
Which Perl module do you want to write about: Compiling modules in general

Please give a short description of the article you want to write. Two to three sentences is fine: How to compile modules from source in difficult environment, e.g no direct access to the internet or CPAN.

**Comment by thibaultduponchelle** [comment]
Article in #193

**Comment by thibaultduponchelle** [comment]
Article in #193

**Comment by thibaultduponchelle** [comment]
day 20

**Comment by oalders** [comment]
Thanks @x1mandi!
