### ISSUE TITLE
At the chart factory

### ISSUE THREAD

**Issue by lichtkind** [perladvent/Perl-Advent#199]
Which Perl module do you want to write about:

Please give a short description of the article you want to write. Two to three sentences is fine:

this is my second article, already submittd at pull request  #198 this is only for further discussions

Thanks

**Comment by thibaultduponchelle** [comment]
👍🏼

**Comment by lichtkind** [comment]
how do i link #198 to this?

**Comment by thibaultduponchelle** [comment]
Day 23

**Comment by oalders** [comment]
Thanks, @lichtkind!
