### ISSUE TITLE
Let the elves import your packages

### ISSUE THREAD

**Issue by bbrtj** [perladvent/Perl-Advent#200]
Which Perl module do you want to write about: `all` (the module, not all the modules 😉 )

Please give a short description of the article you want to write. Two to three sentences is fine: I'm thinking about a short article in a childish style about the module `all`. This is an old module, but very stable and helpful one, while being unknown. The article would babble about santa having no time to manually import all of his packages (classes), and how elves of CPAN help him by recursively walking the directory trees in his `@INC`, importing packages. Then some examples and a plot twist with how it helped me find out I had circular imports (not sure how to write this part without speaking in first person, so I might skip it or just write about little Timmy instead).

**Comment by thibaultduponchelle** [comment]
🎅🏼

**Comment by thibaultduponchelle** [comment]
Merged, thank you a lot @bbrtj

**Comment by thibaultduponchelle** [comment]
day 14
