### ISSUE TITLE
Create professional slideshows with Mojolicious::Plugin::RevealJS

### ISSUE THREAD

**Issue by DragosTrif** [perladvent/Perl-Advent#217]
Which Perl module do you want to write about: Mojolicious::Plugin::RevealJS

#  Create professional slideshows with Mojolicious::Plugin::RevealJS

##  About this talk

1. Install and run a Mojolicious server
2. Configure Mojolicious::Plugin::RevealJS
3. Use html/MarkDown to generate content
4. Add code snippets in your presentation
5. Add notes visible only for the author of the presentation

##  Install and run a Mojolicious server

This assumes you have Perl and cpanm  installed and configured on your machine:
```perl
cpanm Mojolicius Mojolicious::Plugin::RevealJS
```
Now we can generate a Mojolicious lite app:
```perl
mojo generate lite-app slide_show
```
Open the slide_show file with your favorite code editor and add the following code in:
```perl
#!/usr/bin/env perl
use Mojolicious::Lite -signatures;
app->static->paths(['.']);

plugin 'RevealJS';

any '/' => { template => 'presentation', layout => 'revealjs' };

app->start;
```
Create a templates and an examples folder in your current directory:
```bash
mkdir templates
mkdir examples
``` 
## Use html/Markdown to generate content
At this stage we can add a template file inside the templates folder:
```bash
vim templates/presentation.html.ep
```
Now we can paste our first html tags:
```html
<section>
  <h4> Create professional slideshows with Mojolicious::Plugin::RevealJS</h4>
  <p>by Trif Dragos</p>
</section>

<section>
  <h2>About this talk</h2>
    <ul>
    <li>Install and run a Mojolicius server</li>
    <li>Configure Mojolicious::Plugin::RevealJS</li>
    <li>Use html/MarkDown to generate content</li>
    <li>Add code snippets in your presentation</li>
    <li>Add notes visible only for the author of the presentation</li>
  </ul>
</section
```
If you use the following command to start the server, you will be able to access the presentation on your local host:
```bash
morbo slide_show
# Web application available at http://127.0.0.1:3000
```
The exact same result can be archived by using Markdown format:

```
%= markdown_section begin
  #### Create professional slideshows with Mojolicious::Plugin::RevealJS
% end

%= markdown_section begin
  * Install and run a Mojolicius server
  * Configure Mojolicious::Plugin::RevealJS
% end
```
For more details on how to do this in Markdown format you can use this link: [Markdown-Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

## Add code snippets in your presentation
A big plus for this is the fact that you can add code inside your presentation very easily. The 'include_code ' statement specifies the file and  syntax highlighting you want for it.
 
```perl
<section>
  <section>
    %= include_code 'examples/test.pl',  language => 'perl'
  </section>
  <section>
    %= include_code 'examples/app.js', language => 'javascript' 
  </section>
</section>
```
Now create a test.pl file and app.js file in the examples folder and everything will be rendered in your presentation
Lest just say the file with the code snippet is very large and you want just a small part from it to be added to your presentation.
You can accomplish this by adding the 'section' key to the 'include_code':
```perl
%= include_code 'examples/test.pl', language => 'pl', section => 'object_creation'
```
Then inside the 'examples/test.pl' add the following comments to catch only the code desired in your talk:
```perl
use strict;
use warnings;

use lib 'lib';

use Foo;
use feature 'say';

# reveal begin object_creation
my $o = Foo->new();
# reveal end object_creation

$o->print_foo_bar();
$o->test(1);
say $o->test();

say $o->test();
```
This will make only this line visible in your presentation:
```perl
my $o = Foo->new();
```
## Add notes visible only for the author of the presentation:
You can add notes to each slide:

```perl
<section>
  <h4> Create professional slideshows with Mojolicious::Plugin::RevealJS</h4>
  <p>by Trif Dragos</p>
  %= markdown_section begin
  Note:
  my notes
  %end
</section>
```  
If you press 's'  an new window will pop up showing to you the notes you on the current slide. You can control the presentation from this screen and as a bonus is has timer that helps you to know how much time you spent on a slide.

Bibliography:
https://www.perl.com/article/94/2014/6/6/Create-professional-slideshows-in-seconds-with-App-revealup/
https://www.perl.com/article/134/2014/11/13/Advanced-slideshow-maneuvers/

**Comment by DragosTrif** [comment]
HI @oalders this is not reposted. I think you are confused by my previous pull request regarding cucumber.

**Comment by oalders** [comment]
@DragosTrif, I apologize for my misunderstanding. If you could close issues created for reposts, that would be helpful. The process this year has been to create an issue with a short summary of the proposed article and then, after the proposal is accepted, to create a pull request with the content. The PR will give us a chance to review the post and make suggestions etc.

**Comment by DragosTrif** [comment]
HI @oalders reposted stuff are closed.
BR,
Dragos Trif

**Comment by oalders** [comment]
@DragosTrif please open a pull request for your article and link it back to this issue. We can work with you in giving it a bit of Santa backstory. See https://perladvent.org/2016/2016-12-03.html for reference. It simply frames the problem with a holiday them and then gets to the content of the post.

**Comment by DragosTrif** [comment]
@oalders you mean the cucumber one I just closed? Now I'm getting confused :)

**Comment by DragosTrif** [comment]
@oalders here its with the back story https://github.com/perladvent/Perl-Advent/issues/218

**Comment by thibaultduponchelle** [comment]
You created a second "issue", please create a "pull request"

**Comment by DragosTrif** [comment]
Here is the pull request https://github.com/perladvent/Perl-Advent/pull/219

**Comment by thibaultduponchelle** [comment]
day 15
