### ISSUE TITLE
What did Santa forget?

### ISSUE THREAD

**Issue by bbrtj** [perladvent/Perl-Advent#226]
Which Perl module do you want to write about: Value::Diff (my own)

Please give a short description of the article you want to write. Two to three sentences is fine:

Santa is about ready to start his yearly trip around the world! But does he _really_ have everything? Luckily he made a list, and can now use Value::Diff module to see what he is missing.

**Comment by thibaultduponchelle** [comment]
🙏🏼

**Comment by thibaultduponchelle** [comment]
day 9
