### ISSUE TITLE
Article about Excel::Writer::XLSX

### ISSUE THREAD

**Issue by x1mandi** [perladvent/Perl-Advent#228]
Which Perl module do you want to write about: Excel::Writer::XLSX

Please give a short description of the article you want to write. Two to three sentences is fine:
I saw an article about Spreadsheet::WriteExcel from the 2001 Advent Calendar. I was thinking: Why not write an article about the mighty successor Excel::Writer::XLSX, which will introduce the module, and cover some basic functionalities.

**Comment by thibaultduponchelle** [comment]
🕺🏼

**Comment by x1mandi** [comment]
@thibaultduponchelle I have my other PR open, how can I add my new article?

**Comment by thibaultduponchelle** [comment]
@x1mandi yes a new branch please

**Comment by x1mandi** [comment]
@thibaultduponchelle Branch done. #232

**Comment by thibaultduponchelle** [comment]
Day 26

**Comment by oalders** [comment]
Thanks, @x1mandi!
