### ISSUE TITLE
MooseX::Getopt saves Christmas

### ISSUE THREAD

**Issue by fleetfootmike** [perladvent/Perl-Advent#230]
Which Perl module do you want to write about: MooseX::Getopt

Please give a short description of the article you want to write. Two to three sentences is fine:

A quick (and hopefully light-hearted) demonstration of how to use MooseX::Getopt to parse command line options. Covers the basics but by design doesn't go into too much detail.

**Comment by thibaultduponchelle** [comment]
🎅🏼 

#229

**Comment by thibaultduponchelle** [comment]
@fleetfootmike Published today! See [day 2](https://perladvent.org/2022/2022-12-02.html)
