### ISSUE TITLE
How to wrap a camel?

### ISSUE THREAD

**Issue by G4Vi** [perladvent/Perl-Advent#234]
Which Perl module do you want to write about: Perl::Dist::APPerl

Please give a short description of the article you want to write. Two to three sentences is fine:

Once again the elves are up to the tricky task of wrapping a camel. They've gotten reports their previous camel presents have been difficult to move by sleigh and unwrap. Santa has given special instructions on how to wrap them this year. A quick demonstration on how to package perl scripts into cross-platform single binary applications using Perl::Dist::APPerl.

**Comment by oalders** [comment]
It's possible that your article could be entry 26 as we're getting quite close. If you're ok with possibly being a bonus article (which would be great), we'd love to go ahead with this.

**Comment by G4Vi** [comment]
I'm in! I'll get a draft into a PR tonight. pre-draft: https://gist.github.com/G4Vi/3aecef4071f915c5ba264f4a86a0ca8d

**Comment by thibaultduponchelle** [comment]
day 22
