### ISSUE TITLE
Forks have failing workflows

### ISSUE THREAD

**Issue by openstrike** [perladvent/Perl-Advent#250]
The forks of this repo (well, my fork anyway) have the github actions which this one has and this morning this gave me a failure notice for the `Deploy` workflow. That's fair enough since the forked repo shouldn't be deploying anything.

I don't use github actions myself (barely use github at all these days) but expect there would be some way to specify not to run such actions on forks by default. That would be ideal.

**Comment by oalders** [comment]
@openstrike do you have a link to the failed run that I can look at?

**Comment by openstrike** [comment]
Sure, it's this one here: https://github.com/openstrike/Perl-Advent/actions/runs/3588342819

**Comment by oalders** [comment]
Could you try add a condition to the build that it just runs for the main repo? There's an example [here](https://github.com/actions/runner/issues/859)

So, something like:

```yaml
if: "github.repository == 'perladvent/Perl-Advent'
```

If that stops the build from firing at midnight, could you create a PR for that?

**Comment by openstrike** [comment]
Condition added in https://github.com/openstrike/Perl-Advent/commit/3a39bfcb5992bd78280590dff58bd5315328239d

I've omitted the leading double quote as that looked wrong to me and my YAML syntax highlighter - hope that's right.

**Comment by openstrike** [comment]
Still failed. Does this change need to be in the `main` branch?

**Comment by openstrike** [comment]
Still no joy after merging into master. Here is the file: https://github.com/openstrike/Perl-Advent/blob/master/.github/workflows/build.yml and here is the failing job: https://github.com/openstrike/Perl-Advent/actions/runs/3597786101/jobs/6068744429

Is everyone else seeing this in their forks or is it only me?

**Comment by oalders** [comment]
I'm wondering why your main branch is `master` rather than `main`.

**Comment by oalders** [comment]
Not sure if it makes a difference to the workflows, but I found it surprising. I think we renamed the branch back in the summer.

**Comment by oalders** [comment]
I wonder if you deleted your fork and re-forked if it would stop building on the cron.

**Comment by openstrike** [comment]
Good news - the merge into master has done the trick as far as the scheduled actions are concerned. My last test above which failed was on a manually triggered run, so I guess the `if:` clause is ignored for those.

PR incoming.

**Comment by openstrike** [comment]
> Not sure if it makes a difference to the workflows, but I found it surprising. I think we renamed the branch back in the summer.

Yeah, the production branch was always called master previously. A branch rename in the upstream doesn't modify the branch names in the forks by default.

**Comment by oalders** [comment]
Closed via #256
