### ISSUE TITLE
Broken image in 2022-12-03.html

### ISSUE THREAD

**Issue by oalders** [perladvent/Perl-Advent#258]
The personal access token image is not displaying

**Comment by openstrike** [comment]
The image is now displaying but it is far too wide for the styling.

![image](https://user-images.githubusercontent.com/4331674/205515328-803e8263-f289-44d7-a0db-41a01c43252b.png)

**Comment by thibaultduponchelle** [comment]
Should be fixed (along with other issues) with #260

**Comment by openstrike** [comment]
Doesn't appear to be any different, I'm afraid.

And additionally now there is a mixed content warning, which is down to the gravatar being http rather than https.

**Comment by thibaultduponchelle** [comment]
Image is now fixed on my side:
![better](https://user-images.githubusercontent.com/580360/205643954-0139ddcd-5ed3-48a1-8f07-4ef3db916e3e.png)

On smartphone, there is still line number issues + still some text flowing outside of a code block 😢  Both are probably more general issues.

What is the warning you mention @openstrike
