### ISSUE TITLE
Gravatars served over http

### ISSUE THREAD

**Issue by openstrike** [perladvent/Perl-Advent#261]
In the current pages for articles the authors' gravatars are being served over http rather than https resulting in a mixed content warning in the browsers.

eg. at the foot of https://perladvent.org/2022/2022-12-03.html Thibault's gravatar image is included like this:

```<div id='author'>
<img alt='Gravatar Image' style='vertical-align:middle' src=http://www.gravatar.com/avatar/526c1d07817cddaa4055279cf366647a?r=g&s=80&d=retro />
This article contributed by: Thibault DUPONCHELLE &lt;thibault.duponchelle@gmail.com&gt;
</div>
```

The gravatars should be served over https instead.

**Comment by thibaultduponchelle** [comment]
It's something to tweak WWW:AdventCalendar when calling `Gravatar::URL::gravatar_url`, see proposed fix https://github.com/rjbs/WWW-AdventCalendar/pull/8

**Comment by openstrike** [comment]
Has this worked for you? I'm still seeing http gravatars on the live site.

**Comment by thibaultduponchelle** [comment]
> Has this worked for you? I'm still seeing http gravatars on the live site.

Yes, but it's cached, test with incognito window

**Comment by thibaultduponchelle** [comment]
No you're right something is still wrong

**Comment by thibaultduponchelle** [comment]
Is it good for you now? @openstrike

**Comment by openstrike** [comment]
Yes, that's fixed it and cleared the mixed content warning. Nice work.
