### ISSUE TITLE
Indenting code produces unusable code on some platforms

### ISSUE THREAD

**Issue by G4Vi** [perladvent/Perl-Advent#263]
`Pod::Elemental::Transformer::SynHi` transforms leading `\s` into `&nbsp;`. Some platforms turn `&nbsp;` into a regular space `0x20`, but Firefox on Windows preserves it as the UTF-8 bytes `C2A0`.

It appears `Pod::Elemental::Transformer::SynHi`'s behavior is intentional for code in feeds:
https://github.com/rjbs/Pod-Elemental-Transformer-SynHi/blob/master/lib/Pod/Elemental/Transformer/SynHi.pm#L228-L231

**Comment by oalders** [comment]
@G4Vi can you point out the code which is calling `Pod::Elemental::Transformer::SynHi`?

**Comment by G4Vi** [comment]
@oalders I stumbled on `Pod::Elemental::Transformer::SynHi` from the reference in https://github.com/perladvent/Perl-Advent/blob/main/script/new_article#L101-L102 . It appears `WWW::AdventCalendar::Article` doesn't directly use it, but uses `Pod::Elemental::Transformer::PPIHTML` which depends on `Pod::Elemental::Transformer::SynHi`. 

`Pod::Elemental::Transformer::PPIHTML`  does not set `use_standard_wrapper` so `Pod::Elemental::Transformer::SynHi` uses `standard_code_block` to format which does the problematic `&nbsp;` replace.
