### ISSUE TITLE
Multiple issues on smartphone 

### ISSUE THREAD

**Issue by thibaultduponchelle** [perladvent/Perl-Advent#266]
1. Line numbers are not well positioned (green)
2. Text flows out of code block (red)
3. Code block flows out of page container (blue)

![terrible](https://user-images.githubusercontent.com/580360/205842546-cd679620-b714-4d97-85a5-f921829b48b4.png)

**Comment by openstrike** [comment]
Using DDG on Android the line numbers are fine, so that seems to be browser/platform dependent.

The wide content (red and blue) still blows out the formatting, though.

**Comment by thibaultduponchelle** [comment]
+ image overflow
