### ISSUE TITLE
DBIx::Class helper modules

### ISSUE THREAD

**Issue by GeekRuthie** [perladvent/Perl-Advent#289]
Rather than writing about a single module, I'll give a quick look at a number of helper modules for DBIx::Class, which make using DBIx Class easier, semantically-friendly, and more-easy to maintain.

"Santa's Helpers?"

**Comment by oalders** [comment]
That's a great title. Looking forward to it! 🤶🏻 🎅🏻

**Comment by oalders** [comment]
This is a friendly reminder that December is almost here and there is still time to submit your article. If you have a target date in mind for submitting, please update this ticket so that we can get an accurate count of incoming articles. Happy blogging!

**Comment by oalders** [comment]
Scheduled for Dec 11!
