### ISSUE TITLE
Sequentially Consistent Santa

### ISSUE THREAD

**Issue by oodler577** [perladvent/Perl-Advent#290]
(***reverted to original***)

Which Perl module do you want to write about:

Updating tho `Dispatch::Fu`. If time permits, I'll submit a second for `Sub::Genius`.

Sub::Genius

Please give a short description of the article you want to write. Two to three sentences is fine:

Sub::Genius is a module that takes a "plan" of subroutine execution orderings with potentially expressed concurrency, and generates equivalent sequential orderings that may then be used to make a series of pipeline-d calls to the scheduled subroutines. My article will feature Santa fretting over a schedule that seems to require he be in 2 or more places at once, only to be saved by the janitor elf who's been dabbling in Perl on his time off.

**Comment by oalders** [comment]
I did not know about this module. Looking forward to hearing about it. 😀

**Comment by oodler577** [comment]
Working on this over the break ..

**Comment by oalders** [comment]
This is a friendly reminder that December is almost here and there is still time to submit your article. If you have a target date in mind for submitting, please update this ticket so that we can get an accurate count of incoming articles. Happy blogging!

**Comment by oodler577** [comment]
Hey! Will be trying to get a draft out by tomorrow (11/28) sometime. Sorry for the delay!

**Comment by briandfoy** [comment]
Better yet, make a new issue and leave this one in place so you can come back to it.

**Comment by oalders** [comment]
This has been scheduled for Dec 17. The Pod parser had some problems, so I made some minor edits. We really should be catching that in CI before the articles are merged, but that's a project for another day. 😄
