### ISSUE TITLE
Who's That Clicking At The Window?

### ISSUE THREAD

**Issue by saiftynet** [perladvent/Perl-Advent#291]
GUIDeFATE

A short guide to rustling up an GUI Interface without knowing much about GUIs.  Suggesting a story line in which Santa wants to access a database of children on fancy new laptop that has replaced his 200 year old steam powered  workstation. Of course he wants to to do this on a fancy modern GUI and dispense with his old command line teletyping tools.  The GUI Elf is on his break so he has to rely on a more aged coding elf, who himself only just learnt how to use a graphical desktop and had progressed onto using Notepad to write Perl code.  How will he manage?

**Comment by oalders** [comment]
Excellent! 🖥️

**Comment by saiftynet** [comment]
how does one submit the article?

**Comment by oalders** [comment]
Good question. I need to update the README for 2023. When that is done, I'll ping you here.

**Comment by oalders** [comment]
@saiftynet https://github.com/perladvent/Perl-Advent#authors

I don't think we have a good way right now of previewing the articles in the actual calendar. At least, there's no good documented way of doing that. We should look into that. @thibaultduponchelle did you have a good workflow for previewing the articles?

**Comment by oalders** [comment]
This is a friendly reminder that December is almost here and there is still time to submit your article. If you have a target date in mind for submitting, please update this ticket so that we can get an accurate count of incoming articles. Happy blogging!

**Comment by saiftynet** [comment]
@oalders Have attempted to create a pull request for the article.  Wasn't sure what this is going to look like, but here goes!  There is an image I would like to include, have put it in the incoming folder as well as in share/static/...the image is inserted using `for :html` and then  a `div` containing the image

**Comment by oalders** [comment]
I've merged this at the command line via https://github.com/perladvent/Perl-Advent/pull/348

The image is somewhat too wide for the layout, but I don't have the time to mess around with that today. This will be published on 2023-12-08

Thank you so much, @saiftynet!
