### ISSUE TITLE
Arango::Tango

### ISSUE THREAD

**Issue by ambs** [perladvent/Perl-Advent#294]
Which Perl module do you want to write about: Arango::Tango

Please give a short description of the article you want to write. Two to three sentences is fine:

Describe what is ArangoDB, the way Arango::Tango is written to easily allow extensibility, and a brief example of how to use it.
The idea is to both explain what the module is about and how to use it, but also try to gather more users.

**Comment by oalders** [comment]
Thanks, @ambs! We look forward to reading this.

**Comment by ambs** [comment]
@oalders and @briandfoy, can I publish an extended version of the article in my blog after it is shown in the advent calendar?
Also, from what I've seen in previous year's posts, the articles are quite small. Is there a limit, or suggestion, or am I free to write while I'm inspired?

**Comment by ambs** [comment]
Well, here goes a first proposal: https://gist.github.com/ambs/80101e8092ff63acf23b507538bbf2e6

**Comment by oalders** [comment]
> can I publish an extended version of the article in my blog after it is shown in the advent calendar?

Absolutely.

>  Is there a limit, or suggestion, or am I free to write while I'm inspired?

If an article looks like it could be split into multiple parts, we might suggest that, but in general, please feel free to be creative with the article and we'll figure out how best to present it.

**Comment by oalders** [comment]
@ambs would you like to create a Pull Request for your proposal? Instructions are at https://github.com/perladvent/Perl-Advent#authors

**Comment by ambs** [comment]
@oalders will do.  I suppose I should use a temporary name for the pod file.

**Comment by ambs** [comment]
Added to #309

**Comment by oalders** [comment]
Closed via #309
