### ISSUE TITLE
may I reserve a seat at the table?

### ISSUE THREAD

**Issue by garu** [perladvent/Perl-Advent#295]
Which Perl module do you want to write about: I'm not sure yet! 😱 

Maybe this is not the right place or way to do this, but I just wanted to say I *want* to write something, but I'm not sure what to write about.

* I'd love to write about Test2, which is recently added to core (in blead). I think there is probably one, or more advent articles about it in the past, but damn that dist is sweet and needs more people using it;

* I'd love to write about the extra security info the CPANSEC-WG is adding to MetaCPAN, but only if we are able to release it (no sense writing about something that is not there yet);

* I'd love to write about a new super secret dist I'm working on and hope to release before december 1st (it needs a bit of tweaking before it's production ready);

* I'd love to write about optional-chaining in Perl, but realistically I don't think I'll be able to finish implementing AND getting it into core until (this) christmas. If I do, it's definitely worth it I think. 

* If all else fail, or if there is a scarcity of articles close to the deadline, I can also write about ENV::Util, which is a nice little module maybe more people should know about.

Does any of the above appeal to the AdventCal moderators? Since the submission deadline is closing in, I'd love the feedback so I can direct my focus (or just let it go and move on 😛).

Happy Holidays! 🎄 ✨

**Comment by briandfoy** [comment]
+1 for ENV::Util

**Comment by oalders** [comment]
Hi @garu! `Env::Util` looks to be pretty useful, so I'd be interested in that for sure. `Test2` also great. There's some potential in there for a short guide to migrating older tests to `Test2` as one approach you might take. I think they're all great suggestions, though.

**Comment by garu** [comment]
Thank you @briandfoy and @oalders for your positive feedback. For the sake of organization I'm going to close this issue and open two others, one for Test2 and another for ENV::Util.

Cheers!
