### ISSUE TITLE
ENV::Util

### ISSUE THREAD

**Issue by garu** [perladvent/Perl-Advent#297]
Which Perl module do you want to write about: **ENV::Util**

Please give a short description of the article you want to write. Two to three sentences is fine:

This is a simple, lightweight and yet very useful module for easily handling environment variables and dotenv (".env") files in Perl 5 projects of any size. I think more people should add it to their toolbelt.

Full disclosure: I wrote it 😉

**Comment by oalders** [comment]
This is a friendly reminder that December is almost here and there is still time to submit your article. If you have a target date in mind for submitting, please update this ticket so that we can get an accurate count of incoming articles. Happy blogging!

**Comment by oalders** [comment]
Thanks again, @garu! Scheduled for 2023-12-20
