### ISSUE TITLE
Santa tackles Bitcoin

### ISSUE THREAD

**Issue by bbrtj** [perladvent/Perl-Advent#298]
Which Perl module do you want to write about: Bitcoin::Crypto

Please give a short description of the article you want to write. Two to three sentences is fine:

This should be quite fun: More and more kids include Bitcoin in their letters to Santa. But how can this be done logistically? Even magical elves can't print Bitcoin and it's not something you can immediately wrap into a present. No - you need a plan, and you need software.

**Comment by oalders** [comment]
Thanks @bbrtj. We look forward to it!
