### ISSUE TITLE
HTML/XSS scrubbing and file upload validation in Catalyst

### ISSUE THREAD

**Issue by bigpresh** [perladvent/Perl-Advent#299]
Which Perl module do you want to write about:
[Catalyst::Plugin::HTML::Scrubber](https://metacpan.org/pod/Catalyst::Plugin::HTML::Scrubber), [Catalyst::Plugin::CheckFileUploadTypes](https://metacpan.org/pod/Catalyst::Plugin::CheckFileUploadTypes)

Please give a short description of the article you want to write. Two to three sentences is fine:
I have a rough draft of a post about our search at $work for a decent way to scrub/sanitise HTML/XSS from API parameters, finding Catalyst::Plugin::HTML::Scrubber and eventually adopting it and releasing new versions with the new features we needed, and also on implementing file upload checking and releasing Catalyst::Plugin::CheckFileUploadTypes.

Nothing earth-shattering or amazingly interesting, but it'd fill a day :)

**Comment by openstrike** [comment]
Sounds good to me. There will be other people facing the same issue no doubt and for them your article likely will be amazingly interesting.

Thank you for adopting and maintaining this dist.

**Comment by oalders** [comment]
Sounds great, @bigpresh! Please proceed at your convenience.

**Comment by bigpresh** [comment]
Just as an update, this is well underway, just need to find some time to finish adding a bit more to it and proof-reading, then I'll have a PR winging its merry way to you.

**Comment by oalders** [comment]
This is a friendly reminder that December is almost here and there is still time to submit your article. If you have a target date in mind for submitting, please update this ticket so that we can get an accurate count of incoming articles. Happy blogging!

**Comment by bigpresh** [comment]
Indeed - where has all that time gone?  PR #317 raised so what I have already is visible, I hope to find a bit of time tonight if I have a functioning brain to attempt to polish it up a bit further as it's a bit short, dry and uninteresting as it stands.
