### ISSUE TITLE
Quick introduction to App::Timer

### ISSUE THREAD

**Issue by manwar** [perladvent/Perl-Advent#300]
Which Perl module do you want to write about: App::Timer

Please give a short description of the article you want to write. Two to three sentences is fine:
I created the distribution to help me with avoid repeating the code for my other distributions on MetaCPAN. It is going to be short and simple. It would be great to see how others deal with this issue.

**Comment by oalders** [comment]
Thanks, @manwar! I'm looking forward to this.

**Comment by oalders** [comment]
This is a friendly reminder that December is almost here and there is still time to submit your article. If you have a target date in mind for submitting, please update this ticket so that we can get an accurate count of incoming articles. Happy blogging!

**Comment by oalders** [comment]
Closed via #352
