### ISSUE TITLE
Trimming audio files with Nama

### ISSUE THREAD

**Issue by bolangi** [perladvent/Perl-Advent#301]
Which Perl module do you want to write about:

Audio::Nama

Please give a short description of the article you want to write. Two to three sentences is fine:

To trim the commercials out of  radio show, one doesn't need to use a heavy-weight application like Pro-Tools, Ardour or Audacity. Nama is a lightweight recorder/editor/mixer (basically a DAW) with a terminal interface. It's useful on machines with limited resources, or when for accessibility or convenience reasons one prefers text commands to working with GUI menus.

**Comment by oalders** [comment]
I did not know about `Audio::Nama`. I look forward to hearing about it!

**Comment by oalders** [comment]
This is a friendly reminder that December is almost here and there is still time to submit your article. If you have a target date in mind for submitting, please update this ticket so that we can get an accurate count of incoming articles. Happy blogging!

**Comment by bolangi** [comment]
Thank you very much. I'm still in, appreciate the
opportunity to get some exposure for my project (and
motivation for the extra feature or three.) I think later
will be better for me.

Say the 17th to the 20th. 

On Sat, Nov 25, 2023 at 08:23:54AM -0800, Olaf Alders wrote:
> This is a friendly reminder that December is almost here and there is still time to submit your article. If you have a target date in mind for submitting, please update this ticket so that we can get an accurate count of incoming articles. Happy blogging!
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/perladvent/Perl-Advent/issues/301#issuecomment-1826370412
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
Joel Roth

**Comment by oalders** [comment]
Thanks for the update. Keeping in mind that there may be revisions required and that people get busy in December, I would say the best chance of success would be to get the PR in at least a week to 10 days before the publish date you'd like.

**Comment by openstrike** [comment]
Yes, the pull requests should be against this repo which is hopefully the one you have forked. See [the submit FAQ](https://github.com/perladvent/Perl-Advent/blob/main/FAQ-submit.mkdn) for formatting and other handy guidelines.

**Comment by bolangi** [comment]
I'm hard at it, hope to finish real soon now.

On Sun, Nov 26, 2023 at 04:30:19PM -0800, Olaf Alders wrote:
> Thanks for the update. Keeping in mind that there may be revisions required and that people get busy in December, I would say the best chance of success would be to get the PR in at least a week to 10 days before the publish date you'd like.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/perladvent/Perl-Advent/issues/301#issuecomment-1826960780
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
Joel Roth

**Comment by bolangi** [comment]
Hi Olaf,

I think I've finished the article (finally this time). I moved all the
techobabble to the end.  Will add a graphic tommorrow. 

Let me know when you have a date, if possible, as I want to make
sure to do a cpan release before then. 

Thank you for your patience.


-- 
Joel Roth

**Comment by oalders** [comment]
Hi @bolangi,

I could schedule this as soon as the 17th or 18th, I think. There's not a lot of finished work in pipeline. Let me know if that works for you?

**Comment by bolangi** [comment]
Hi olaf,

The 18th will be great.

Thanks 


On Fri, Dec 15, 2023 at 06:28:57AM -0800, Olaf Alders wrote:
> Hi @bolangi,
> 
> I could schedule this as soon as the 17th or 18th, I think. There's not a lot of finished work in pipeline. Let me know if that works for you?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/perladvent/Perl-Advent/issues/301#issuecomment-1857973001
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
Joel Roth

**Comment by oalders** [comment]
\o/
