### ISSUE TITLE
todo web app 

### ISSUE THREAD

**Issue by ktown007** [perladvent/Perl-Advent#302]
Which Perl module do you want to write about:
Dancer2 and HTMX 
Please give a short description of the article you want to write. Two to three sentences is fine:
An example of super simple todo app using no javascript. Learn a bit of HTMX and Dancer2.  The intent was not the golf it but it turned out to not need much code, this simplicity speaks to the power of these tools. 

https://gist.github.com/ktown007/d3c45c70fc76a0785edf848cab209cbf

**Comment by oalders** [comment]
That's quite succinct. I look forward to the article!

**Comment by ktown007** [comment]
I added `naughty.md` to the gist. This could have a part 2 with Planet Scale db and a part 3 with cloud docker edge deploy.

**Comment by oalders** [comment]
Multi-part articles are encouraged this year. That sounds like a great idea.

**Comment by ktown007** [comment]
added v2.list.mustache and v2.todo.pl to use planetscale mysql db in place of the array.

**Comment by ktown007** [comment]
I created a Dockerfile and launched on fly.io with the planetscale db.  It works! Cold start is 1.5 seconds.

**Comment by oalders** [comment]
When you're ready, feel free to create a pull request for the article.

**Comment by ktown007** [comment]
I put the files here: https://github.com/ktown007/todoapp
with a free planetscale.com and fly.io accounts hosting is really simple and quick.

**Comment by oalders** [comment]
What do you think about moving the `todoapp` repo to the `perladvent` org and me giving you permissions on the repo in the new location? My concern is about linking to resources that we have no control over. If it's in the org, then we'll always know where to find it.

**Comment by oalders** [comment]
Great! We now need to convert this to an incoming article so that we can merge it and schedule a publish date. The instructions for that are at https://github.com/perladvent/Perl-Advent/#authors

**Comment by oalders** [comment]
Oof. Please ignore. I'm juggling a lot of PRs here. :)

**Comment by oalders** [comment]
Closed via #307
