### ISSUE TITLE
Net::SCP use cases

### ISSUE THREAD

**Issue by x1mandi** [perladvent/Perl-Advent#308]
Which Perl module do you want to write about: Net::SCP

Please give a short description of the article you want to write. Two to three sentences is fine:
Brief introduction about the module and some use cases. Not sure about the backstory yet, it will work out itself on the fly ;)

**Comment by oalders** [comment]
Sounds great!

**Comment by oalders** [comment]
This is a friendly reminder that December is almost here and there is still time to submit your article. If you have a target date in mind for submitting, please update this ticket so that we can get an accurate count of incoming articles. Happy blogging!

**Comment by x1mandi** [comment]
Hi Olaf,

Sorry I was sick in the last few weeks and could not concentrate on my
article.
Do you already have the required number of articles? If so, I will postpone
mine for next year, otherwise, please let me know and I will complete mine
by the end of this week.

Kind regards,
Csaba

**Comment by oalders** [comment]
I'm going to close this as I'm trying to figure out how many more articles we need and I'm not confident this one will be completed. If I'm wrong, please let me know and we can re-open the ticket.
