### ISSUE TITLE
Moose attribute shortcuts for everyone

### ISSUE THREAD

**Issue by bbrtj** [perladvent/Perl-Advent#334]
Which Perl module do you want to write about: Mooish::AttributeBuilder

Please give a short description of the article you want to write. Two to three sentences is fine:
I've no clue how to turn it into a Christmas story, but since there is shortage of articles this year I'll happily write a short article about my Mooish::AttributeBuilder module. It's a no-dependency helper for a wide range of modules using Moose syntax, so I think it will be well received judging from my similar entry last year.

**Comment by oalders** [comment]
I look forward to it!
