### ISSUE TITLE
St. Nick's Reindeers Need More H2O!

### ISSUE THREAD

**Issue by oodler577** [perladvent/Perl-Advent#388]
Which Perl module do you want to write about:

Util::H2O::More

Please give a short description of the article you want to write. Two to three sentences is fine:

Last year's _[St. Nick's Reindeers Need H2O!](https://perladvent.org/2022/2022-12-06.html)_ ended with a brief mention of [Util::H2O::More](https://metacpan.org/pod/Util::H2O::More). This story will focus on some features I reach for through this module, which is basically a collection of tools that I used on an almost daily basis myself.

**Comment by oalders** [comment]
Let's do it!

**Comment by oalders** [comment]
Scheduled for 2023-12-22 \o/
