### ISSUE TITLE
Santa wields his Perl and OpenMP skills

### ISSUE THREAD

**Issue by oodler577** [perladvent/Perl-Advent#420]
Which Perl module do you want to write about:

OpenMP

Please give a short description of the article you want to write. Two to three sentences is fine:

I am going to write an article where Santa solves some last minute conundrum by writing parallelized C code using OpenMP that's embedded in a Perl script using Inline::C.

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by oalders** [comment]
Hello! 😁  This is your *late November* reminder that we are going live in just a few days. Could you update this ticket with a target date for your first draft? 📆

**Comment by oodler577** [comment]
@oalders I do not know, I am thinking Monday or Tuesday 12/2 or 12/3. Sorry for the delay.

**Comment by oodler577** [comment]
@oalders - there's text section that is not displaying, I think I made up a `=begin` type maybe? Can I just issue a PR update and get the page rebuilt next time you publish?

**Comment by oalders** [comment]
Yes. I'll merge ASAP.

**Comment by oodler577** [comment]
@oalders, I branched off of #main and I think removed the right bits, #519
 - thank you!

**Comment by oalders** [comment]
Article was already merged. \o/
