### ISSUE TITLE
While you're waiting for Christmas

### ISSUE THREAD

**Issue by Ovid** [perladvent/Perl-Advent#421]
Which Perl module do you want to write about: [MooseX::Extended](https://metacpan.org/pod/MooseX::Extended)

Please give a short description of the article you want to write. Two to three sentences is fine:

For those looking for a "better" OOP system in Perl, there's been a lot of excitement about the new [class](https://perldoc.perl.org/perlclass) keyword for Perl, based on the [Corinna project](https://github.com/Perl-Apollo/Corinna). Unfortunately, it will take a while to build and probably be in experimental status for at least two years after that.

[MooseX::Extended](https://metacpan.org/pod/MooseX::Extended) was written to give you a powerful object system _now_, so long as you use Perl `v5.20.0` or better.

**Comment by oalders** [comment]
Closing as this was done a while back. Thank you so much, @Ovid!
