### ISSUE TITLE
Article about GitHub Actions

### ISSUE THREAD

**Issue by davorg** [perladvent/Perl-Advent#423]
Which Perl module do you want to write about: It's not a Perl module, it'll be about using Github Actions to maintain a CPAN module.

Please give a short description of the article you want to write. Two to three sentences is fine:

I think I'll want to touch on three main points:

1. Standardised GitHub Actions to [run tests, measure coverage, run linters](https://github.com/PerlToolsTeam/github_workflows) and things like that
2. Standardised GitHub Actions to release modules to CPAN
3. The use of [CPAN Dashboard](https://cpandashboard.com/) to monitor your CPAN modules

**Comment by thibaultduponchelle** [comment]
Look forward to read your article 👍🏼 

Some resources for your point 2 (but maybe you know about them):
- [action-upload-to-cpan](https://github.com/thibaultduponchelle/action-upload-to-cpan) 
- [action-publish-cpan](https://github.com/cucumber/action-publish-cpan) (for distzilla based distributions)

**Comment by briandfoy** [comment]
Steal anything you like from mine: https://github.com/briandfoy/github_workflows The one to release on GitHub might be the most interesting. 

I also have some interesting ones in https://github.com/briandfoy/PerlPowerTools for labeling issues as they come in, and https://github.com/briandfoy/business-isbn-data has one to notice external file changes and make a PR off that.

Of course, promote your book :)

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by davorg** [comment]
I wanna say the end of next weekend (24 Nov). But I'm secretly hoping to delight you by getting it in earlier than that.

**Comment by oalders** [comment]
Closed via #452
