### ISSUE TITLE
Object::Pad + App::Standup::Diary proposal

### ISSUE THREAD

**Issue by smonff** [perladvent/Perl-Advent#424]
> Which Perl module do you want to write about

[App::Diary](https://codeberg.org/smonff/Diary) (not released on CPAN, yet). It's a simple tool I use since 2021 to automate the creation of a daily file where I mostly take notes to stay organized and prepare meetings.

It's my testbed app for experimenting with Object::Pad (note I said Object::Pad and not the core Class feature).

> Please give a short description of the article you want to write

I'd like to tell a short advent-like story where a character use it to stay focus and organized in a difficult situation like the Christmas delivery deadline.

It would be focused on the Object::Pad basic features discovery, and presenting how to use the diary app.

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by smonff** [comment]
I'll commit my draft tomorrow (Saturday). And a more polished version the day after.

**Comment by smonff** [comment]
Ready for review on #467 , thanks.

**Comment by oalders** [comment]
Closed via #467. Thanks, @smonff!
