### ISSUE TITLE
Routing Framework in Perl

### ISSUE THREAD

**Issue by manwar** [perladvent/Perl-Advent#425]
Which Perl module would you like to hear about?

I would like to talk about about my CPAN module Map::Tube.

Please give a short description of the module you'd like to hear about. Two to
three sentences is fine.

I would like to talk about all possible solutions with regard to routing as below:

a) Map::Tube::CLI - Command line tool setup and show the working
b) Map::Tube::API - Use REST API to get the routing feature
c) Map::Tube::Server - Setup Routing Server locally and show the working

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by oalders** [comment]
Hello! 😁  This is your *late November* reminder that we are going live in just a few days. Could you update this ticket with a target date for your first draft? 📆

**Comment by oalders** [comment]
Closed via #458. Thanks, @manwar!
