### ISSUE TITLE
Observability using OpenTelemetry

### ISSUE THREAD

**Issue by itcharlie** [perladvent/Perl-Advent#427]
Which Perl module would you like to hear about?

https://metacpan.org/pod/OpenTelemetry

Please give a short description of the module you'd like to hear about. Two to
three sentences is fine.

An article giving an example of implementing an Observability solution using OpenTelemetry , a web application ( preferably in Perl - * Mojo/Dancer/Catalyst ) and a log analysis tool like ( Splunk, DataDog, SumoLogic, etc ) 

Here is an online resource that explains Observability further by Splunk:  ( https://www.splunk.com/en_us/blog/learn/observability.html ) 

"Observability uses three types of [telemetry data](https://www.splunk.com/en_us/blog/learn/what-is-telemetry.html) — [metrics, logs and traces](https://www.splunk.com/en_us/blog/learn/melt-metrics-events-logs-traces.html) — to provide deep visibility into distributed systems and allow teams to get to the [root cause](https://www.splunk.com/en_us/blog/learn/root-cause-analysis.html) of a multitude of issues and improve the system’s performance."

**Comment by jjatria** [comment]
Sweet! I'll be happy to help with this :popcorn:

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by oalders** [comment]
Hello! 😁  This is your *late November* reminder that we are going live in just a few days. Could you update this ticket with a target date for your first draft? 📆

**Comment by jjatria** [comment]
I don't want to step on any toes, but I'd be happy to put something together if @itcharlie is running low on TUITs.

**Comment by oalders** [comment]
@jjatria I've just sent a message to @itcharlie on LinkedIn, but I don't know how often he checks that. Having said that, if you'd like to put something together, I don't have a problem with two articles on OpenTelemetry. We are still short on material. 😄

**Comment by itcharlie** [comment]
Hi guys!

When I made this issue I was actually requesting for an article on the subject. Presently I am not working on an article.

**Comment by oalders** [comment]
Looking forward to it @jjatria!

**Comment by jjatria** [comment]
@oalders Just sent in a PR! Super late, but it's there :see_no_evil:

**Comment by oalders** [comment]
Closed via #511
