### ISSUE TITLE
PerlGPT, An AI's First Christmas

### ISSUE THREAD

**Issue by wbraswell** [perladvent/Perl-Advent#428]
**Which Perl module do you want to write about:**

PerlGPT

**Please give a short description of the article you want to write. Two to three sentences is fine:**

On Christmas 2024 we will all receive a very special gift from Santa - the PerlGPT artificial intelligence platform!
AI is the way of the future, and that future is now for all the good Perl programmers around the world.
He's makin' a list and checkin' it twice, so get ready 'cuz Santa Claus is comin' tonight!

(Full article will include runnable Perl source code examples, as usual.)

**Comment by oalders** [comment]
Thanks for this. I've accepted your other proposal to start with. I'm generally going to hold off on multiple articles from the same author until I get a better idea of how many articles to expect this year.

**Comment by oalders** [comment]
Closing as we're on track to hit our article count.
