### ISSUE TITLE
A Perl Type of Christmas Story

### ISSUE THREAD

**Issue by wbraswell** [perladvent/Perl-Advent#429]
**Which Perl module do you want to write about:**

Perl::Types

**Please give a short description of the article you want to write. Two to three sentences is fine:**

On the very first Christmas night, there were only a very small **_number_** of **_characters_** present, such as humble shepherds and farm animals.  A short **_string_** of camels crossed the desert, following a shining star.  An **_array_** of angels sang in the heavenly host, peace on Earth and goodwill toward men!

(Full article will include runnable Perl source code examples, as usual.)

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by oalders** [comment]
Hello! 😁  This is your *late November* reminder that we are going live in just a few days. Could you update this ticket with a target date for your first draft? 📆

**Comment by oalders** [comment]
Closing as we're on track to hit our article count.
