### ISSUE TITLE
Parallelizing Data Intensive Applications for scientific computing using Perl

### ISSUE THREAD

**Issue by chrisarg** [perladvent/Perl-Advent#432]
Which Perl module do you want to write about:
Inline::C
Please give a short description of the article you want to write. Two to three sentences is fine:

Demonstrate the use of the OpenMP framework to parallelize data intensive applications in scientific computing. Will illustrate the use of multiple packages (e.g. Alien, OpenMP::Environment, Inline::C) for such a parallelization and memory management approaches, with specific examples from biological sequence/text analysis.

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by oalders** [comment]
Hello! 😁  This is your *late November* reminder that we are going live in just a few days. Could you update this ticket with a target date for your first draft? 📆

**Comment by chrisarg** [comment]
Hi Olaf
Probably the week prior to Xmas eg Dec 20

Christos

**Comment by oalders** [comment]
🤞🏻

**Comment by chrisarg** [comment]
I (think) I submitted the piece :)

**Comment by oalders** [comment]
Closed via #507. Thank you, @chrisarg!
