### ISSUE TITLE
Using Valiant validations and HTML form generation with Catalyst and DBIx::Class

### ISSUE THREAD

**Issue by jjn1056** [perladvent/Perl-Advent#433]
Which Perl module do you want to write about: Valiant

Please give a short description of the article you want to write. Two to three sentences is fine:

An overview of how to use Valiant to decorate your DBIC result sources with validation logic and then using it in a web page controlled by Catalyst.   Includes how to use Valiant::HTML::Formbuilder for form generation.

This will include a short survey of existing similar options on CPAN with pros and cons.

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by oalders** [comment]
Hello! 😁  This is your *late November* reminder that we are going live in just a few days. Could you update this ticket with a target date for your first draft? 📆

**Comment by oalders** [comment]
Closed via #485
