### ISSUE TITLE
Bumping your code's Perl version

### ISSUE THREAD

**Issue by book** [perladvent/Perl-Advent#434]
Which Perl module do you want to write about: `Perl::Version::Bumper` (to be released) 

Please give a short description of the article you want to write. Two to three sentences is fine:

The article would describe what `use VERSION` actually does, how Perl handles backward and forward compatibility, and how to use the above module to safely "bump" any Perl code to the desired version.

**Comment by briandfoy** [comment]
Not that it has to be part of the article, but I use [PPI::App::ppi_version::BDFOY](https://metacpan.org/pod/PPI::App::ppi_version::BDFOY). Curious to see what you've come up with.

**Comment by book** [comment]
> Curious to see what you've come up with.

The repository is here: <https://github.com/book/Perl-Version-Bumper/>. 

I'd recommend looking at the test data to see the line of transformation it does.

**Comment by book** [comment]
Also, before embarking on this journey, I _did_ look for prior art. It seems I wasn't looking hard enough, or using the wrong keywords.

**Comment by book** [comment]
And I just realized that my description is very confusing. :sweat_smile: 

This module is not about changing: `our $VERSION = 1.23;` into `our $VERSION = 1.24;` in random Perl files. It's about bumping the declared Perl language version of some source code to a more recent version.

For example, when asked to "bump" the following code snippet to `v5.36`:

```
use v5.20;
use warnings;
use experimental 'signatures';
use feature 'lexical_subs';
no warnings 'experimental::lexical_subs';
no indirect;
```

The module will rewrite it to:

```
use v5.36;
```

Because it knows that:
* `warnings` are enabled by the `:5.36` feature bundle
* the `signatures` feature is enabled in the `:5.36` feature bundle (and it knows about `experimental`)
* the `lexical_subs` feature is enabled in the `:5.26` feature bundle (and it knows about experimental warnings)
* the `indirect` feature is disabled in the `:5.36` feature bundle, and the `indirect` module is a compatibility module for the `indirect` feature

**Comment by briandfoy** [comment]
That sounds pretty cool, along with Perl::MinimumVersion. I'd like to read this article.

**Comment by choroba** [comment]
As the author of [Syntax::Construct](https://perldoc.pl/Syntax::Construct), I'm interested, too.

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by oalders** [comment]
Hello! 😁  This is your *late November* reminder that we are going live in just a few days. Could you update this ticket with a target date for your first draft? 📆

**Comment by oalders** [comment]
Article was already merged. \o/
