### ISSUE TITLE
Using Rx to validate data structures, YAML, or JSON

### ISSUE THREAD

**Issue by briandfoy** [perladvent/Perl-Advent#435]
I've been using Data::Rx to validate YAML files for cpan-security-advisories. I'll write a short demonstration of that, including custom data types.

FWIW, I have this strong deja vu feeling that I've written this article before but it doesn't show up in the search for this repo.

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by briandfoy** [comment]
The first draft is now in PR #444
