### ISSUE TITLE
Annotating Christmas Trees

### ISSUE THREAD

**Issue by choroba** [perladvent/Perl-Advent#437]
Which Perl module do you want to write about:

Treex::PML

Please give a short description of the article you want to write. Two to three sentences is fine:

I want to present a module that propels the tree editor TrEd. I talked about TrEd in my TPRC 2024 talk, but unlike there, I'd like to only present the basics in the article.

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by oalders** [comment]
Hello! 😁  This is your *late November* reminder that we are going live in just a few days. Could you update this ticket with a target date for your first draft? 📆

**Comment by choroba** [comment]
Sorry, I had health problems (vestibular vertigo for those interested). I'm getting better, I'll try to write something over the weekend.

**Comment by oalders** [comment]
I wish you a speedy recovery, @choroba. If you're not feeling up to it, that's certainly understandable, but we are also happy to have your entry this year if it doesn't cause you extra stress. No pressure from here. This is supposed to be a fun activity.
