### ISSUE TITLE
Perl, my child, is love in Github Actions

### ISSUE THREAD

**Issue by JJ** [perladvent/Perl-Advent#438]
Perl has been and is the glue that bind together many different and disparate command line applications; all and everyone can use it to create data munging pipelines that just work. That has made it a mainstay in many operating systems... Including those that can be found in Github workflow runners. These not only include Perl, but a good and nice series of Perl modules that will give you no work at all to create fast-and-dirty github actions that can be glued together, in the same way as Linux commands are.
But if that's not enough, you can always rely on CPAN and packers, as well as Github Action templates avaiable in GitHub. This article will be about that: what support is out there to create GitHub actions with Perl, and how to do it in no time flat, applying Perl love to your DevOps pipelines.

**Comment by oalders** [comment]
Sounds great!

**Comment by oalders** [comment]
Hello! This is your mid-November reminder that Advent is fast approaching. The first articles will go live in less than 3 weeks. We are very much looking forward to preparing your article for publication. If you could update this ticket with an ETA for your first draft that would be very helpful when it comes to planning ahead for editing, proofreading etc. 🌲🤶🎅🧝

**Comment by oalders** [comment]
Hello! 😁  This is your *late November* reminder that we are going live in just a few days. Could you update this ticket with a target date for your first draft? 📆

**Comment by JJ** [comment]
I'm almost there. Thanks for the reminder

**Comment by JJ** [comment]
Almost there. Will be ready this evening or tomorrow at the latest.
