### ISSUE TITLE
Investigating a new respiratory virus outbreak in Santa's workshop

### ISSUE THREAD

**Issue by mdperry** [perladvent/Perl-Advent#449]
Which Perl module do you want to write about:  There is not a specific CPAN module that performs this task, however my code may make use of some of the better known modules in Bio::Perl (but I may just use a bespoke solution instead).

Please give a short description of the article you want to write. Two to three sentences is fine: The task is to transform the numbering system for some short DNA fragments from one strain of Respiratory Syncytial Virus (subtype A) to the genomic coordinates of a related but distinct strain of RSV-A.  Once this is complete it will make it possible to rerun existing workflows and create better (more accurate, hopefully more useful) phylogenetic trees from the elve's nasopharyngeal swabs.

**Comment by oalders** [comment]
Article was already merged. \o/
