### ISSUE TITLE
Using Valiant for Validations in Agendum: A Deep Dive into DBIx::Class Integration

### ISSUE THREAD

**Issue by jjn1056** [perladvent/Perl-Advent#484]
Valiant

Using the included DBIC integrations, how to write validations on DBIx::Class result classes using Valiant, as well as a an introduction to Agendum, a demo web application for Catalyst used for experimenting with new approaches to using this classic framework.

**Comment by jjn1056** [comment]
article PR for review: https://github.com/perladvent/Perl-Advent/pull/485

**Comment by oalders** [comment]
Closed via #485
