### ISSUE TITLE
Problem with unicode in the article https://perladvent.org/2024/2024-12-15.html 

### ISSUE THREAD

**Issue by bessarabov** [perladvent/Perl-Advent#505]
Here is a screenshot what i see on the page https://perladvent.org/2024/2024-12-15.html :

![Screen Shot 2024-12-15 at 14 41 23](https://github.com/user-attachments/assets/5770215e-410d-4ecf-aa8a-e4a58cc5c863)

In the source code there is no such problem https://github.com/perladvent/Perl-Advent/blob/main/2024/articles/2024-12-15.pod :

![Screen Shot 2024-12-15 at 14 42 57](https://github.com/user-attachments/assets/46b40bee-2d06-4d01-b6d8-5876a0e38fb0)

**Comment by oalders** [comment]
Oof. Thank you, @bessarabov! This seems to be an issue with how we are using https://metacpan.org/pod/Text::VimColor That's my best guess.

**Comment by bessarabov** [comment]
Thank you for the quick solution! I really appreciate your support.
